apiVersion: v1
kind: Service
metadata:
  name: games-service
  namespace: jenkins  # Specify the namespace here
spec:
  type: LoadBalancer
  selector:
    app: games-station
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8080